# Generated by Django 5.0.2 on 2024-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('street_number', models.IntegerField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('cuit', models.IntegerField()),
                ('store_phone', models.IntegerField()),
            ],
        ),
    ]
